esphome:
  name: ph-example
  friendly_name: ph-example

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "***********************************"

# Enable OTA updates
ota:
  password: "***********************"

# Configure WiFi
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Configure fallback hotspot (enabled if WiFi connection fails)
  ap:
    ssid: "ph-example Fallback Hotspot"
    password: "*********"

# Enable captive portal
captive_portal:

# Configure I2C bus
i2c:
  sda: 5
  scl: 6

# Configure ADS1115 ADC
ads1115:
  - address: 0x48

# Configure sensor using ADS1115
sensor:
  - platform: ads1115
    multiplexer: 'A0_GND'
    gain: 6.144
    name: "PH ADS1115 Channel A0-GND"
    update_interval: 20s
    accuracy_decimals: 3
    # Apply linear calibration
    # filters:
    #   - calibrate_linear:
    #       - 1.48 -> 6.86
    #       - 0.95 -> 9.18
